---
title: "Bob's Burgers"
author: "Jo Hardin"
date: "11/19/2024"
format: 
  html:
    from: markdown+emoji
execute:
  warning: false
  message: false
---

```{r}
library(tidyverse) # ggplot, lubridate, dplyr, stringr, readr...
library(bobsburgersR)
library(praise)
```



## The Data

This week we're exploring Bob's Burgers dialogue! Thank you to [Steven Ponce](https://github.com/poncest) for [the data](https://github.com/poncest/bobsburgersR), and a [blog post demonstrating how to visualize the data](https://stevenponce.netlify.app/projects/standalone_visualizations/sa_2024-11-11.html)!

See the [{bobsburgersR} R Package](https://github.com/poncest/bobsburgersR) for the original transcript data, as well as additional information about each episode!


```{r}
episode_metrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-11-19/episode_metrics.csv')
```

```{r}
words <- c("fart", "crap", "toilet", "buns", "diarrhea",
           "poop", "(doo doo)")

list <- str_c("(?i)", str_c(words, collapse = "|"))
list

poop_data <- transcript_data |> 
  filter(str_detect(raw_text, list)) |> 
  filter(!str_detect(raw_text, "(?i)farth"))
```

```{r}
poop_data |> 
  group_by(season, episode) |> 
  summarize(num_wrds = n()) |> 
  full_join(imdb_wikipedia_data, 
            by = c("season", "episode")) |> 
  ggplot(aes(y = num_wrds, x = episode, 
             color = as.factor(season))) + 
  geom_point(size = 3, show.legend = FALSE, alpha = 0.8) + 
  facet_wrap(~season)
```

```{r}
words <- c("burger")

list <- str_c("(?i)", str_c(words, collapse = "|"))
list

other_data <- transcript_data |> 
  drop_na(raw_text) |> 
  mutate(word_in = str_detect(raw_text, list)) 
```

:hamburger:
```{r}
hamburg <- "\U1F354"
```

```{r}
# devtools::install_github("yjunechoe/junebug")
#junebug::font_hoise("Font Awesome 5 Free")
other_data |> 
  group_by(season, episode) |> 
  summarize(num_wrds = sum(word_in)) |> 
  full_join(imdb_wikipedia_data, 
            by = c("season", "episode")) |> 
  ggplot(aes(y = num_wrds, x = episode)) + 
  geom_text(aes(label = "cat"), size = 5, family = "Font Awesome 5 Free Solid") +
  facet_wrap(~season)
```


```{r}
imdb_wikipedia_data |> 
  group_by(wikipedia_directed_by) |> 
  summarize(num_ep = n()) |> 
  arrange(desc(num_ep))
```



```{r}
praise()
```

